### ISSUE TITLE
Image texture is not reactive

### ISSUE THREAD

**Issue by danbulant** [khonsulabs/cushy#171]
Changing the texture of an image (As Image::new takes Dynamic<AnyTexture>) works but doesn't trigger a re-render or re-layout (if the image size changes).

Furthermore, kind of oddly, AnyTexture doesn't implement PartialEq and so one can't use .set directly. I personally think it's fine to use the map function directly, but maybe there could be a function like set_unchecked that would always trigger a rerender even if the value didn't change. Or describe this behaviour in docs.

**Comment by ecton** [comment]
Thank you for your feedback! Have you tested the reactivity on the main branch? I ask because [a couple of weeks ago](https://github.com/khonsulabs/cushy/commit/e0df3b001730678ec7e0764b9dd73c5f417f7ed7#diff-52423bae3c0b0557303dacef032b787acbae87d6968c130f652e422403133814R158) I think I fixed this, but I didn't create a changelog note about it.

`AnyTexture` needing PartialEq I agree with! I added it to `LazyTexture` while working on the project I did the linked change for, but didn't notice the usability issue with `AnyTexture`. I'll get that added to Kludgine.

I'll also look into adding tips about non-PartialEq types somewhere. My favorite way to update them is `*foo.lock() = bar`, but using map is also a good approach.

**Comment by danbulant** [comment]
I haven't tried the main branch, just skimmed the src as I didn't notice that there are a lot of changes not released yet..
Changing the dep to main branch didn't work, I got some errors with dependencies, but that's likely my problem and I haven't given it enough time yet.

Thanks for the notes regarding lock, I missed that function and I saw map being used internally by set.
