### ISSUE TITLE
Improve data widget so it's possible to access the data.

### ISSUE THREAD

**Issue by hydra** [khonsulabs/cushy#214]
The data widget had me confused when I tried to use it, it's description reads:

> The Data widget is a widget that can contain an arbitrary value. The widget does not display or occupy any space. This is useful for ensuring a resource isn't dropped while a user interface is displayed.

All well and good, the data lives as long as the widget.

When I tried to use it, I thought: "great! that's exactly what I need", however, it's API doesn't provide a way to access the data.

The only example I found that use it, 'progress.rs', stores either an animation or a tuple of a callback and a progress, but never tries to access the wrapped values, that I can see.

```rust
...
                Data::new_wrapping((callback, progress), ease_out_probe).make_widget()
            }
            ReadOnly::Constant(_) => {
                Data::new_wrapping(indeterminant_animation, ease_out_probe).make_widget()
            }
```

At the time I thought would be nice if there was some way of accessing the data belonging to the widget, so that given a widget instance, you can access it's data;  For instance, a widget contained in a widget list.  In my 'close tab' use case I wanted to store a `TabKey` for a 'Tab Button' widget instance in the `WidgetList` for a tab bar, so that when iterating over the elements in the `WidgetList` I could remove the one matching a candidate `TabKey`.  Instead, I had to manage separate struct members for the TabBar, one called `tab_buttons` a `Dynamic<WidgetList>`, and one called `tab_keys` a `Vec<TabKey>` that contains an ordered list of corresponding tab keys for each widget in the widget list, and then I have to `.zip` the iterators of each in the `close_tab` method.

**Comment by ecton** [comment]
This is an interesting idea. To me, Cushy serves as the "View" layer of an application. It doesn't really own the data. So for me the code that is creating the `Data` widget already has the data, wouldn't it be a lot easier to return it than to wrap it up in a widget and try to extract it via downcasting a widget? Ie, instead of storing the widget instance, why not store what the data is holding? Or the widget and that data?

As you pasted from the docs, the purpose of the widget is to provide a place to hold something that otherwise would get dropped, but needs to be held while the user interface is open. That's why the example never accesses the stored data: it's not needed. It's being used to make sure that certain values are kept alive as long as the widget hierarchy it belongs to is alive, and once it's cleaned up that resource can be dropped as well.

I'm happy to add a function to give access to the data, I just wanted to explain the current design more since it sounded like it was puzzling.

**Comment by hydra** [comment]
Thanks for the commit and response.  I'm still finding my way around the framework and haven't yet delved into creating widgets. 

The idea of a downcasting widget and the struct might work, I need to revisit the WidgetList API and do some more reading/learning.  I think I tried downcasting the widget in the hopes that the data widget somehow implemented downcasting, but it didn't and the downcast failed.

Is it somehow possible to expand the Data widget further so that it *does* support downcasting to the data?

**Comment by ecton** [comment]
```rust
    let data = Data::new(String::from("hello")).make_widget();
    dbg!(data.lock().downcast_ref::<Data<String>>().unwrap().data());
```

This works, so I think the `WidgetInstance` you have probably is another widget kind than the data itself. Downcasing only works on the direct type of widget that it was before it was wrapped into a `WidgetInstance`.
